/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OtraGrafica;

import Graphics.MainFrame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eduardobaldivieso
 */
public class Menucito extends javax.swing.JFrame {

    /**
     * Creates new form Menucito
     */
 

    public Menucito() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnIniGame = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();
        Principalito = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setText("Usuario:");
        MenuPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        MenuPrincipal.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, 30));

        btnIniGame.setText("Iniciar");
        btnIniGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniGameActionPerformed(evt);
            }
        });
        MenuPrincipal.add(btnIniGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        btnUnirse.setText("Unirse");
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });
        MenuPrincipal.add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        getContentPane().add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Principalito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Principalito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniGameActionPerformed

        MainFrame mf = null;
        try {
            mf = new MainFrame(txtName.getText());
        } catch (IOException ex) {
            Logger.getLogger(Menucito.class.getName()).log(Level.SEVERE, null, ex);
        }
        mf.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_btnIniGameActionPerformed

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        try {
            MainFrame mf = new MainFrame(txtName.getText());
            mf.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Menucito.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnUnirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menucito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel Principalito;
    private javax.swing.JButton btnIniGame;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
